services:
  api:
    build:
      context: .
    container_name: devsecops-task-api
    environment:
      PORT: 3000
      NODE_ENV: development
      MONGODB_URI: mongodb://mongo:27017/devsecops_tasks
      GITHUB_REPOSITORY: ${GITHUB_REPOSITORY:-dahmaniamine/devsecops-task-api}
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: devsecops-task-mongo
    environment:
      MONGO_INITDB_DATABASE: devsecops_tasks
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  mongo_data:
