services:
  - type: web
    name: devsecops-task-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
