services:
  - type: web
    name: secureship-lite
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: GITHUB_REPOSITORY
        value: dahmaniamine/devsecops-task-api
      - key: MONGODB_URI
        sync: false
      - key: GITHUB_TOKEN
        sync: false
